big_anus:
big_anus_top:
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte big_anus_0, big_anus_1, big_anus_2, big_anus_3, big_anus_4, big_anus_5, big_anus_6, big_anus_7, big_anus_8, big_anus_9, big_anus_10, big_anus_11
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte big_anus_12, big_anus_13, big_anus_14, big_anus_15, big_anus_16, big_anus_17, big_anus_18, big_anus_19, big_anus_20, big_anus_21, big_anus_22, big_anus_23
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte big_anus_24, big_anus_25, big_anus_26, big_anus_27, big_anus_28, big_anus_29, big_anus_30, big_anus_31, big_anus_32, big_anus_33, big_anus_34, big_anus_35
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte big_anus_36, big_anus_37, big_anus_38, big_anus_39, big_anus_40, big_anus_41, big_anus_42, big_anus_43, big_anus_44, big_anus_45, big_anus_46, big_anus_47
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte big_anus_48, big_anus_49, big_anus_50, big_anus_51, big_anus_52, big_anus_53, big_anus_54, big_anus_55, big_anus_56, big_anus_57, big_anus_58, big_anus_59
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte big_anus_60, big_anus_61, big_anus_62, big_anus_63, big_anus_64, big_anus_65, big_anus_66, big_anus_67, big_anus_68, big_anus_69, big_anus_70, big_anus_71
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0

big_anus_bottom:
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte big_anus_72, big_anus_73, big_anus_74, big_anus_75, big_anus_76, big_anus_77, big_anus_78, big_anus_79, big_anus_80, big_anus_81, big_anus_82, big_anus_83
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte big_anus_84, big_anus_85, big_anus_86, big_anus_87, big_anus_88, big_anus_89, big_anus_90, big_anus_91, big_anus_92, big_anus_93, big_anus_94, big_anus_95
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte big_anus_96, big_anus_97, big_anus_98, big_anus_99, big_anus_100, big_anus_101, big_anus_102, big_anus_103, big_anus_104, big_anus_105, big_anus_106, big_anus_107
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte big_anus_108, big_anus_109, big_anus_110, big_anus_111, big_anus_112, big_anus_113, big_anus_114, big_anus_115, big_anus_116, big_anus_117, big_anus_118, big_anus_119
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte big_anus_120, big_anus_121, big_anus_122, big_anus_123, big_anus_124, big_anus_125, big_anus_126, big_anus_127, big_anus_128, big_anus_129, big_anus_130, big_anus_131
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte big_anus_132, big_anus_133, big_anus_134, big_anus_135, big_anus_136, big_anus_137, big_anus_138, big_anus_139, big_anus_140, big_anus_141, big_anus_142, big_anus_143
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte big_anus_144, big_anus_145, big_anus_146, big_anus_147, big_anus_148, big_anus_149, big_anus_150, big_anus_151, big_anus_152, big_anus_153, big_anus_154, big_anus_155
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0

sm_anus:
sm_anus_top:
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte sm_anus_0, sm_anus_1, sm_anus_2, sm_anus_3, sm_anus_4, sm_anus_5, sm_anus_6, sm_anus_7, sm_anus_8, sm_anus_9
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte sm_anus_10, sm_anus_11, sm_anus_12, sm_anus_13, sm_anus_14, sm_anus_15, sm_anus_16, sm_anus_17, sm_anus_18, sm_anus_19
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte sm_anus_20, sm_anus_21, sm_anus_22, sm_anus_23, sm_anus_24, sm_anus_25, sm_anus_26, sm_anus_27, sm_anus_28, sm_anus_29
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte sm_anus_30, sm_anus_31, sm_anus_32, sm_anus_33, sm_anus_34, sm_anus_35, sm_anus_36, sm_anus_37, sm_anus_38, sm_anus_39
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte sm_anus_40, sm_anus_41, sm_anus_42, sm_anus_43, sm_anus_44, sm_anus_45, sm_anus_46, sm_anus_47, sm_anus_48, sm_anus_49
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte sm_anus_50, sm_anus_51, sm_anus_52, sm_anus_53, sm_anus_54, sm_anus_55, sm_anus_56, sm_anus_57, sm_anus_58, sm_anus_59
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0

sm_anus_bottom:
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte sm_anus_60, sm_anus_61, sm_anus_62, sm_anus_63, sm_anus_64, sm_anus_65, sm_anus_66, sm_anus_67, sm_anus_68, sm_anus_69
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte sm_anus_70, sm_anus_71, sm_anus_72, sm_anus_73, sm_anus_74, sm_anus_75, sm_anus_76, sm_anus_77, sm_anus_78, sm_anus_79
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte sm_anus_80, sm_anus_81, sm_anus_82, sm_anus_83, sm_anus_84, sm_anus_85, sm_anus_86, sm_anus_87, sm_anus_88, sm_anus_89
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte sm_anus_90, sm_anus_91, sm_anus_92, sm_anus_93, sm_anus_94, sm_anus_95, sm_anus_96, sm_anus_97, sm_anus_98, sm_anus_99
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0
  .byte sm_anus_100, sm_anus_101, sm_anus_102, sm_anus_103, sm_anus_104, sm_anus_105, sm_anus_106, sm_anus_107, sm_anus_108, sm_anus_109
  .byte solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0, solids_0


blurb_tiles_1:
  .byte chr_w, chr_h, chr_a, chr_t, solids_0, chr_i, chr_s, solids_0, chr_a, solids_0, chr_b, chr_l, chr_o, chr_o, chr_d, chr_y
blurb_tiles_2:
  .byte chr_a, chr_n, chr_e, chr_s, solids_0, chr_d, chr_o, chr_i, chr_n, chr_g, solids_0, chr_h, chr_e, chr_r, chr_e, chr_qm

anus_attrs:
  .byte %00000000, %00000000, %00000000, %00000000, %00000000, %00000000, %00000000, %00000000
  .byte %00000000, %00000000, %00000000, %00000000, %00000000, %00000000, %00000000, %00000000

