main_palette:
  .byte $17,$08,$26,$25 ;; main palette
  .byte $17,$08,$18,$28
  .byte $1a,$39,$3A,$0f
  .byte $00,$30,$00,$00 ;; splash palette

  .byte $36,$07,$17,$27 ; drip palette
  .byte $01,$02,$38,$3C
  .byte $01,$1C,$15,$14
  .byte $01,$02,$38,$3C

splash_palette:
  .byte $0d, $30, $16, $00 ; default
  .byte $0d,$0d,$00,$00 ; scrolling track
  .byte $0d,$16,$30,$07 ; splash title
  .byte $0d,$00,$00,$00

  .byte $0d,$0d,$0d,$0d
  .byte $0d,$00,$00,$00
  .byte $0d,$00,$00,$00
  .byte $0d,$00,$00,$00


