splash_title:
splash_title_top:
  .byte solids_0,solids_0,solids_0,solids_0,solids_0
  .byte splash_0,splash_1,splash_2,splash_3,splash_4,splash_5,splash_6,splash_7,splash_8,splash_9,splash_10,splash_11,splash_12,splash_13,splash_14,splash_15,splash_16,splash_17,splash_18,splash_19,splash_20,splash_21
  .byte solids_0,solids_0,solids_0,solids_0,solids_0
  .byte solids_0,solids_0,solids_0,solids_0,solids_0
  .byte splash_22,splash_23,splash_24,splash_25,splash_26,splash_27,splash_28,splash_29,splash_30,splash_31,splash_32,splash_33,splash_34,splash_35,splash_36,splash_37,splash_38,splash_39,splash_40,splash_41,splash_42,splash_43
  .byte solids_0,solids_0,solids_0,solids_0,solids_0
  .byte solids_0,solids_0,solids_0,solids_0,solids_0
  .byte splash_44,splash_45,splash_46,splash_47,splash_48,splash_49,splash_50,splash_51,splash_52,splash_53,splash_54,splash_55,splash_56,splash_57,splash_58,splash_59,splash_60,splash_61,splash_62,splash_63,splash_64,splash_65
  .byte solids_0,solids_0,solids_0,solids_0,solids_0
  .byte solids_0,solids_0,solids_0,solids_0,solids_0
  .byte splash_66,splash_67,splash_68,splash_69,splash_70,splash_71,splash_72,splash_73,splash_74,splash_75,splash_76,splash_77,splash_78,splash_79,splash_80,splash_81,splash_82,splash_83,splash_84,splash_85,splash_86,splash_87
  .byte solids_0,solids_0,solids_0,solids_0,solids_0
  .byte solids_0,solids_0,solids_0,solids_0,solids_0
  .byte splash_88,splash_89,splash_90,splash_91,splash_92,splash_93,splash_94,splash_95,splash_96,splash_97,splash_98,splash_99,splash_100,splash_101,splash_102,splash_103,splash_104,splash_105,splash_106,splash_107,splash_108,splash_109
  .byte solids_0,solids_0,solids_0,solids_0,solids_0

splash_title_bottom:
  .byte solids_0,solids_0,solids_0,solids_0,solids_0
  .byte splash_110,splash_111,splash_112,splash_113,splash_114,splash_115,splash_116,splash_117,splash_118,splash_119,splash_120,splash_121,splash_122,splash_123,splash_124,splash_125,splash_126,splash_127,splash_128,splash_129,splash_130,splash_131
  .byte solids_0,solids_0,solids_0,solids_0,solids_0
  .byte solids_0,solids_0,solids_0,solids_0,solids_0
  .byte splash_132,splash_133,splash_134,splash_135,splash_136,splash_137,splash_138,splash_139,splash_140,splash_141,splash_142,splash_143,splash_144,splash_145,splash_146,splash_147,splash_148,splash_149,splash_150,splash_151,splash_152,splash_153
  .byte solids_0,solids_0,solids_0,solids_0,solids_0
  .byte solids_0,solids_0,solids_0,solids_0,solids_0
  .byte splash_154,splash_155,splash_156,splash_157,splash_158,splash_159,splash_160,splash_161,splash_162,splash_163,splash_164,splash_165,splash_166,splash_167,splash_168,splash_169,splash_170,splash_171,splash_172,splash_173,splash_174,splash_175
  .byte solids_0,solids_0,solids_0,solids_0,solids_0
  .byte solids_0,solids_0,solids_0,solids_0,solids_0
  .byte splash_176,splash_177,splash_178,splash_179,splash_180,splash_181,splash_182,splash_183,splash_184,splash_185,splash_186,splash_187,splash_188,splash_189,splash_190,splash_191,splash_192,splash_193,splash_194,splash_195,splash_196,splash_197
  .byte solids_0,solids_0,solids_0,solids_0,solids_0
  .byte solids_0,solids_0,solids_0,solids_0,solids_0
  .byte splash_198,splash_199,splash_200,splash_201,splash_202,splash_203,splash_204,splash_205,splash_206,splash_207,splash_208,splash_209,splash_210,splash_211,splash_212,splash_213,splash_214,splash_215,splash_216,splash_217,splash_218,splash_219
  .byte solids_0,solids_0,solids_0,solids_0,solids_0

splash_press_start: ; 11 bytes
  .byte chr_p, chr_r, chr_e, chr_s, chr_s, solids_0, chr_s, chr_t, chr_a, chr_r, chr_t

splash_attrs:
  .byte %11111111, %11111111, %11111111, %11111111, %11111111, %11111111, %11111111, %11111111
  .byte %11111111, %11111111, %11111111, %11111111, %11111111, %11111111, %11111111, %11111111

